### ISSUE TITLE
Preparing a 3-4 sentence overview of the health.schema.org extension

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#1]
While we are preparing the health.schema.org extension, we need to agree on a short introduction for it. Dan proposed the following short text as starting point.

"The medical extension refines and improves schema.org's medical/healthcare vocabulary that was initially published in 2012 (see http://blog.schema.org/2012/06/health-and-medical-vocabulary-for.html http://schema.org/docs/meddocs.html ). Taking into various integration points post-2012 changes (e.g. Audience, action / muscleAction), it moves schema.org's detailed treatment of medical terminology into a extension called 'med'. "

I need your feedback about it, any edition is higly welcome!

**Comment by davefeg** [comment]
It's that! I just add minor edits:

"The medical extension refines and improves schema.org's medical/healthcare vocabulary that was initially published in 2012 (see http://blog.schema.org/2012/06/health-and-medical-vocabulary-for.html http://schema.org/docs/meddocs.html ). 
Taking into various integration points post-2012 changes (e.g. Audience, action / muscleAction, Enumeration), and with community effort to extend (e.g Medical Encounter, Medical Procedure), and polish existing version, it moves schema.org's detailed treatment of medical vocabulary and terminology into a extension called 'health'. "

That was my 2 cents!
