### ISSUE TITLE
Move from core to extension: consider if we move Place / LocalBusiness -related types

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#14]
Comments from Dan (#2)
We should consider if we move Place / LocalBusiness -related types: Dentist Hospital Optician Pharmacy Physician Clinician etc
(Dentistry vs Dentist?)
(some of these are also person-as-organization awkward)

**Comment by jvandriel** [comment]
I think having proper examples for these will help a lot already. Lead by example so to say.

Now unfortunately I'm no good at Github so I'm not able to add examples myself, but if you want I could write some examples and post 'm here in the comments so somebody else can add them to the extension.

Just let me know what types of examples you'd like to have, preferably with an idea of the types of properties you'd like to see used.

**Comment by twamarc** [comment]
Thanks @jvandriel. Having examples will help an I welcome your help here. can you provide some examples about  those Place/LocalBusiness -related types: Dentist Hospital Optician Pharmacy Physician Clinician? 
This would help to understand the initial intended use and improve it if needed.
To provide them in git hub, just paste them as a comment, ideally in triple quotes to preserve the format. Reading this maybe can help https://help.github.com/articles/github-flavored-markdown/

alternativelly you can share them on mailing list (what I prefer): public-schemed@w3.org

**Comment by jvandriel** [comment]
Just to make sure, are you suggesting we move those Place/LocalBusiness subtypes under `schema.org/MedicalOrganization`?

**Comment by twamarc** [comment]
The question was to consider if we move those ambiguous terms from the schema core to the health extension.
`Dentist` can be the person, but also the place where the dental care is given.

Second question there was to see if it's needed to refine or replace some of those terms like:

`Dentist` to be superseded by `Dentistry`

Q:`Dentistry` can be  the branch of medecine, but also the profession.

So we change an ambiguous term to another ambiguous one.
My initial thoughts was to leave that as it is now, and investigate how to disambiguate in future.
Maybe we will chose one clear definition like  `A technical practitioner who ...` and leave the `place` component.

It becomes even complicated with:
`Optician` to be superseded by `????`

Here we will need however to disambiguate with:

Optometrist
Optometrists are healthcare professionals who provide primary vision care ranging from sight testing and correction to the diagnosis, treatment, and management of vision changes. An optometrist is licensed to practice optometry, which primarily involves performing eye exams and vision tests, prescribing and dispensing corrective lenses, detecting certain eye abnormalities, and prescribing medications for certain eye diseases.

Optician
Opticians are technicians trained to design, verify and fit eyeglass lenses and frames, contact lenses, and other devices to correct eyesight. They use prescriptions supplied by ophthalmologists or optometrists, but do not test vision or write prescriptions for visual correction. Opticians are not permitted to diagnose or treat eye diseases.
Source:http://www.aapos.org/terms/conditions/132

Currently:
Most of the listed are already under `MedicalOrganization`.
And we have already the `:MedicalOrganization :subClassOf :LocalBusiness`.

**Comment by jvandriel** [comment]
I like the idea of moving over the mentioned `schema.org/LocalBusiness` subtypes into the med extension and have them be subtypes of `schema.org/MedicalOrganization`.

That would make it possible to specify `medicalSpecialty > Medicalspecialty > relevantSpecialty > enumeration` to those.

**Comment by jvandriel** [comment]
Related discussion over at the core: https://github.com/schemaorg/schemaorg/issues/806

**Comment by jvandriel** [comment]
_"Q:Dentistry can be the branch of medecine, but also the profession."_

`schema.org/Person` currently doesn't have any property for specifying a person's profession as an entity. The only property it has is `jobTitle` with an expected value of text, eg:

```
<span itemscope itemtype="http://schema.org/Person">
    <span itemprop="honorificPrefix">Dr</span> <span itemprop="name">Ricardo L Rodriguez</span> <span itemprop="honorificSuffix">MD</span>
    <span itemprop="jobTitle">Board Certified Plastic Surgeon</span>
</span>
```

So expressing  a person's profession IMHO isn't something we need to worry about for the medical extension yet, and possible it's a discussion that should be held over at the core first as there have been folks interested in being able to express professions with schema.org.

But if we don't have to take any 'profession' into account for now then we're just left with a subtype of `schema.org/LocalBusiness` and `schema.org/MedicalSpecialty` enumerations, which seems quite workable to me.

_"Here we will need however to disambiguate with"_

According to wikipedia (https://en.wikipedia.org/wiki/Optometry) Optometry is a profession, which isn't part of schema.org yet, so we could skip it...

**Comment by twamarc** [comment]
Decision: see http://www.w3.org/2015/11/06-schemed-minutes.html and https://github.com/schemaorg/schemaorg/issues/492

Summary:
1)Not move all of them but only medical related
2)Improvement in extension:

```
Organization 
        > MedicalOrganization 
```

and 

```
Organization
    > LocalBusiness
        > MedicalBusiness (new class in health extension)
            > Dentist
            > DiagnosticLab
            > Hospital
            > MedicalClinic
            > Optician
            > Pharmacy
            > Physician
            > VeterinaryCare
```

```
Person
    > profession (new predicate in core)
        > Profession (new class in core)
            > MedicalSpecialty
               > Cardiovascular
               > Dentistry
               > etc 
```
