### ISSUE TITLE
Need to disambiguate the Model: |MedicalProcedure |MedicalTherapy |TherapeuticProcedure

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#21]
Current version

```
:TherapeuticProcedure :subClassOf :MedicalProcedure
:TherapeuticProcedure :subClassOf :MedicalTherapy
:MedicalTherapy :subClassOf :MedicalEntity
```

Suggested

```
: MedicalTherapy :subClassOf :TherapeuticProcedure
: TherapeuticProcedure :subClassOf :MedicalProcedure
```

Rationale:
MedicalTherapy is a procedure and describes taking medications for treatment. So it fitts under therapeuticProcedure class, this one being itself under medicalProcedure class.
This would be a first step of rebuilding the MedicalProcedure entity to comply with common models and other medical terminologies: Snomed and HL7 standards

**Comment by jvandriel** [comment]
The only thing I have a problem with is that the `adverseOutcome` and `seriousAdverseOutcome` properties can't be used for `schema.org/MedicalProcedure`. After all, procedures can have adverse outcomes as well yet it currently isn't possible to specify these properties for a `schema.org/MedicalProcedure` unless one uses a multi-type entity like `["MedicalProcedure","MedicalTherapy"]`.

An entity which is a bit strange to specify as `schema.org/MedicalTherapy` already is a subtype, yet something like a Abdominoplasty can hardly be considered a therapy.

**Comment by twamarc** [comment]
The `adverseOutcome` and `seriousAdverseOutcome` properties will keep being used only for `schema.org/MedicalTherapy`. 
Unless there's a use case demand, we do not attach those properties to `schema.org/MedicalProcedure`

**Comment by jvandriel** [comment]
Oh I actually have a use case: http://www.cosmeticsurg.net/procedures/tummy-tuck/ (as well as other medical procedures on that site - which I recently started work on).

For this document I've currently used the MTE I described, while I'd prefer to be able to specify `adverseOutcome` and `seriousAdverseOutcome` for the `schema.org/MedicalProcedure` itself.

**Comment by twamarc** [comment]
Currently the two predicates `adverseOutcome` and  `seriousAdverseOutcome` were not associated to`schema.org/MedicalProcedure` itself. Maybe we need to create another issue for extending the domain of the two properties with `MedicalProcedure`, what is arguable clinically saying. 
This will then replace the  `medicalTheapy` because a property of higher level class is the property of all children. No need to use the multi-type.

**Comment by jvandriel** [comment]
I opened up a new issue: #32

**Comment by twamarc** [comment]
+1
This (#32) needs to be handled separately.

**Comment by twamarc** [comment]
Decision: see http://www.w3.org/2015/11/06-schemed-minutes.html and #492

Summary:
1)Not move them from core to extension
2)Improvement in extension:
Current version

```
:TherapeuticProcedure :subClassOf :MedicalProcedure
:TherapeuticProcedure :subClassOf :MedicalTherapy
:MedicalTherapy :subClassOf :MedicalEntity
```

Suggested

```
: MedicalTherapy :subClassOf :TherapeuticProcedure
: TherapeuticProcedure :subClassOf :MedicalProcedure
```

Rationale:
MedicalTherapy is a procedure and describes taking medications for treatment. So it fitts under therapeuticProcedure class, this one being itself under medicalProcedure class.
This would be a first step of rebuilding the MedicalProcedure entity to comply with common models and other medical terminologies: Snomed and HL7 standards
