### ISSUE TITLE
Would like to see deeper Health Insurance markup

### ISSUE THREAD

**Issue by ccorak** [twamarc/ScheMed#3]
I am new to the community. I apologize if this has been a subject discussed in the past that I am not aware of. But in the even it has not been discussed, I thought I'd start a discussion. Thanks for your time.

With research and shopping behaviors changing in healthcare (including health coverage), it's assumed that more and more healthcare content will be created to help users navigate this changing landscape. I think adding / expanding health insurance as a type or extension of health.schema.org would be very helpful.

I see that the following both exist:
http://demoschemed.appspot.com/guarantor
http://demoschemed.appspot.com/insurance

I like the idea of being able to describe at the organizational or personal levels. But it seems as though health insurance could be described in far more detail. Could we describe the type of plan / coverage? High-deductible, Individual vs Family, Medicaid, Medicare, Vision, Dental, co-pays, coverage regions... While I think this would be valuable for those that offer coverage, I also believe it would be helpful on the provider side. Hospitals, physicians, urgent care, aggregators could markup their content when describing how their care interacts with coverage.

Thank you for your time!

**Comment by twamarc** [comment]
Hi @ccorak ,
Any proposal of limited higly useful class/properties? In hierarchy I mean.
Just like Mark Woon did in #6 . This helps to follow up and to take a concrete conclusion.

**Comment by ccorak** [comment]
Hello @twamarc ,

Thanks for taking the time to review.  Here is a rough thought on possible structure. Definitely needs massaging. 

Some of the below information is taken from Wikipedia’s structure around Health Insurance.
https://en.wikipedia.org/wiki/Health_insurance_in_the_United_States 

HealthInsurance or HealthCoverage or MedicalInsurance
- GeneralMedicalCoverage
  - InsuranceType
    - HealthMaintenanceOrganization (HMO)
    - PPO
    - POS
    - ...
  - PlanType 
    - IndividualPlan
    - FamilyPlan
    - HighDeductiblePlan
    - LimitedBenefitPlan
    - ShortTermPlan
    - LongTerm (Disability)
    - Medicare
    - ...
- Vision
- Dental
- Medicare
  - MedicareAdvantage
  - PartD
- HealthInsuranceAssistance
  - Medicaid
  - SCHIP (state children’s health insurance program)
  - Subsidies
- CollegeSponsoredCoverage
- SupplementalCoverage
- EmployerCoverage
  - RetireePlans
  - PartTime or Seasonal
- Reform (?)
  - FederalCoverage
  - StateCoverage
  - HealthInsuranceExchange
  - ..?

Organization
- HealthInsuranceProvider
- HealthInsuranceBroker

Could also file categories under Private vs Commercial insurance (but this may not be truly necessary).

Within Plans, could include these Types / Properties:
- Description
- PlanProvider
- Product
  - Offer
- Benefits
  - Pharmacy
    - DrugList
- Enrollment
  - EnrollmentPeriod
  - Application
  - …
- Payment (Fees / Premiums)
  - Deductibles
  - Copay
    *...
- PreexistingCondition
- QualifyingLifeEvents

**Comment by twamarc** [comment]
Thanks @ccorak. 
I forwarded this to the #Healthcare_Schema_Vocabulary_Community_Group mailing list to enable discussions there (https://www.w3.org/community/schemed/).

**Comment by ccorak** [comment]
Thank you @twamarc !  Let me know how I can help. I appreciate the time you all put into this community.

**Comment by twamarc** [comment]
/cc 
From: David Portnoy
Marc,
Happy to talk.  We're creating schemas driven by legislation in the U.S.  This schema includes healthcare provider directory, demographics, quality attributes, and health insurance coverage.  Ultimately, it's intended to help consumers navigate the healthcare system.  We focus more on interoperability among the many layers of industry participants than on vocabulary.

Let me know your thoughts on how we should (or shouldn't) coordinate.  Thanks!

The full thread here:
https://lists.w3.org/Archives/Public/public-schemed/2015Jul/0004.html

**Comment by ccorak** [comment]
Thank you @twamarc .

I have reviewed the health plan and provider proposal that is currently being worked out at https://docs.google.com/document/d/11JiYc9PIxIzmgGCSDOUvvkvmmwl0-UvUos2twIEnP64/edit?usp=sharing . 

I am very excited that the group is working towards a September submission (and meeting the last week of August). In this documentation, I love the tie back to federal plan IDs. I love the granularity in the provider section as well. One thing I think could see some benefits from could be either providing state level markup, or possibly a more general markup in place of advanced markup at the state level.

It appears as though this markup is extending relevance to the US federal plans. How does it fit in however with the state exchanges? I agree starting at the federal level makes the most sense, in that the high majority of the states have not created their own version of the exchange. But there are 17 states / areas (including DC) that have. Do federal IDs tie in relevance to state exchanges? If not, there will be 17 states that are unable to take advantage of the federally relevant markup. I understand that we don't have the time / flexibility to create state markup for each exchange. And even if we had time, this may be excessive anyhow. But.... could a more generalized markup (for those not on the federal exchange) allow those states that have created their own exchange to mark their content up as well? Assuming the federal markup isn't 100% relevant to those 17 states, it would be a bummer if this first round of health coverage markup that goes live wouldn't be relevant to 1/3 of the states.

Just as you were suggesting, @twamarc , would a mixture of what I was proposing and what is already being worked out allow all states to markup their content? In addition to compliance with federal regulations, I also believe there will be an even bigger boom of 3rd party sites aimed at making navigating the healthcare system easier (similar to what stride is doing). More markup with extensions to already existing types / properties (eg product, offer, types of organizations...) will aid in a comprehensive understanding.

Could "summary_url" or "marketing_url" be used in reference the URL on a state exchange? Or could a more generalized markup for SameAs reference a state exchange URL?

Thank you all.

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
