### ISSUE TITLE
Expand the domain of adverseOutcome and seriousAdverseOutcome to MedicalProcedure

### ISSUE THREAD

**Issue by jvandriel** [twamarc/ScheMed#32]
I suggest we expand the domain of `adverseOutcome` and `seriousAdverseOutcome` to `schema.org/MedicalProcedure`.

Currently their domain is limited to `schema.org/MedicalTherapy`, yet clinical procedures can have (serious) adverse outcomes as well. Something which this webpage actually describes in structured data: http://www.cosmeticsurg.net/procedures/tummy-tuck/.

And something other sites publish about (by mentioning terms like _risks_, _complications_, _side effects_) without any relevant markup:
http://www.mayoclinic.org/tests-procedures/tummy-tuck/basics/risks/prc-20020325
http://www.webmd.com/beauty/tummy-tuck/cosmetic-procedures-tummy-tuck
http://www.realself.com/guide/tummy-tuck-procedure#Side_Effects

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
