### ISSUE TITLE
Expand the definition of medicalSpecialty

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#34]
Issue opened from  @LeezaRodriguez comment on https://github.com/twamarc/ScheMed/issues/33.

*_Q / *_ Is it possible to clarify the definition of MedicalSpecialty so that is reflects the formal process of training, certification, and licensing?

**Rationale :** I'm afraid that webmasters may apply the term loosely, without knowledge that the designation of a 'MedicalSpecialty' is quite a formal thing. Any person or organization which is tied to a 'MedicalSpecialty' should have formal 'certification' and be 'licensed' in the Medical Specialty. The person or organization with a MedicalSpecialty must have attained training, certification, and licensing from an authority organization to practice medicine in that Medical Specialty.

When a physician asserts himself as a provider of care in a designated Medical Specialty, the consumer (and the AI engine) should be able to parse if that provider is trained/certified/boarded or not. HUGE difference. As the enumerated list of Medical Specialties grows, this really concerns me.

**Current description:** Any specific branch of medical science or practice. Medical specialities include clinical specialties that pertain to particular organ systems and their respective disease states, as well as allied health specialties. Enumerated type.

**Proposed description:** Any specific branch of medical science or practice that a person or organization has formal training, certification and licensing from an authority organization to practice medicine in that Medical Specialty. Medical specialities include clinical specialties that pertain to particular organ systems and their respective disease states, as well as allied health specialties. Enumerated type.

/cc @LeezaRodriguez

**Comment by westurner** [comment]
> *Q / \* Is it possible to clarify the definition of MedicalSpecialty so that is reflects the formal process of training, certification, and licensing?

schema.org/Credential may or may not be added in the schema.org course extension.
- https://github.com/schemaorg/schemaorg/issues/195
  - https://goo.gl/2Sxxy3 "schema document"
  - https://github.com/schemaorg/schemaorg/pull/972
  - http://course.schema-course-extend.appspot.com/

.
- [ ] Credential
  - [ ] Certificate
  - [ ] Degree
  - [...]

**Comment by LeezaRodriguez** [comment]
@westurner  The example use case is to designate this:

John Doe MD
-  Board Certified, Neurology
-  Certified by 'American Board of Psychiatry and Neurology' 
-  Accredited by 'American Board of Medical Specialties (ABMS)' <--this is the oversight organization of any Medical Board , and is critical for consumers to be aware of as there are some 'Medical Boards' that operate in a vacuum with no oversight and little credibility.  In the US, these extraneous Medical Boards have been known to originate from healthcare providers who fail their ABMS Medical Boards, and start their own 'Medical Board' organization .  

In terms of degree, the Medical Specialty certification is conferred after completion of a Residency and completion of Oral and Written Boards. These providers have already completed Medical School years ago.

**Comment by westurner** [comment]
- Thing > Intangible > Credential
  - Credential > Certification
    - [x] name
    - [x] description
    - [x] url
    - [ ] source <Organization> ?
    - [ ] person/target/recipient/earner ?
  - Credential > Certification > Accreditation
    - ibid.

From "Re: Cost" https://lists.w3.org/Archives/Public/public-schema-course-extend/2016Feb/0024.html :

> And then to clarify the real transaction,
> There is an :Offer
> for a :Service
> and/or a :Product (e.g. a :Credential > :OpenBadgesBadgeClass),
> which then, in addition to time and effort Project(:Mission, :Goals,
> :Objectives (%), {Tasks/Actions/...}),
> yields an instance of said Credential,
> per the terms of the Offer for Service and Product.

... As potentially listed in a https://schema.org/OfferCatalog [edit: link]

What else are we failing to model here (where is this schema _lossy_)?:
- Residency
  - should this be an attribute of schema.org/Physician
    - d: schema:Physician (`:Physician`)
    - r: :Organization (is there a more specific type here?)
- Boards
  - {Oral, Written}  # either Enumerations or _potentially mistyped, unvalidate-able_ attributes/properties with a range of `<URL>`

**Comment by westurner** [comment]
re: Credential

from the Schema.org Course Extension "schema document":

> Thing > Intangible > Credential > OpenBadgesBadgeClass
> An OpenBadges BadgeClass.
> - [ ] https://github.com/openbadges/openbadges-specification/issues/9
> - [x] https://twitter.com/philbarker/status/689815591318863872
> 
> Thing > Intangible > Credential > Badge > OpenBadgesBadge
> - [ ] JWS signatures and JSON-LD
>   - see: http://json-ld.org/playground/ > “Event” > “Signed” tab pane (#pane-signed)
> - [ ] JWS signatures and RDFa

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
