### ISSUE TITLE
Improving terms under MedicalSpeciality

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#35]
Thinking how to improve terms defined under `MedicalSpeciality` but labelled as adjectives:
eg. We currently have:
`Surgical` instead of   `Surgery`
`Endocrine` instead of  `Endocrinology`
`Neurologic` instead of  `Neurology`
`Renal` instead of  `Nephrology`
etc.

To be tracked under: https://github.com/schemaorg/schemaorg/issues/492

**Comment by westurner** [comment]
So, IIUC (I'm not sure which RDFa document these are (yet?) defined in):
- [x] http://schema.org/Person
  - [ ] http://schema.org/HealthcareProvider
    - [x] http://schema.org/Physician
      - Thing > Organization > LocalBusiness > MedicalBusiness > Physician 
      - Thing > Organization > MedicalOrganization > Physician 
      - Thing > Place > LocalBusiness > MedicalBusiness > Physician
      - [ ] Thing > Person > Physician
    - [ ] Nurse
      - [ ] Category:Nurse_subtypes
      - 
      - https://en.wikipedia.org/wiki/List_of_nursing_specialties
- [ ] a HealthcareProvider may have zero or more MedicalSpecialty _enumerations_
  - (though OWL cardinality is not supported here)
    - https://en.wikipedia.org/wiki/Cardinality
      - https://www.w3.org/TR/owl-ref/#CardinalityRestriction
      - https://www.w3.org/TR/owl2-new-features/#F5:_Property_Qualified_Cardinality_Restrictions
- [ ] ? a MedicalSpecialty may or may not imply a MedicalSpecialtyTitle (e.g. a neurologist specializes in neurology)

[edit] Nurse, checkboxes for current task state

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
