### ISSUE TITLE
Renaming properties that have generic names

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#36]
Comment from @mfhepp:
https://github.com/schemaorg/schemaorg/issues/492

The following properties have pretty generic names. There is a risk that we define them in the narrow sense of the medical / health domain. I would recommend to rename them so that it becomes clear that they are meant in the specific sense of this domain:
- action,
- algorithm
- aspect
- availableIn
- availableService
- branch
- cause, causeOf
- code, codeValue, codingSystem
- comprisedOf, connectedTo
- cost, costCategory, costCurrency, costOrigin, costPerUnit - also, how does this relate to PriceSpecification
- diagram
- frequency
- function
- manufacturer
- origin, originatesFrom,
- overview
- partOfSystem
- runsTo
- source, sourcedFrom
- purpose
- status
- usesDevice, warning

**Comment by davefeg** [comment]
It seems logic (just for cleaning purposes) to leave those in core (and deprecate them) and only move the renamed one in the extension. 

@twamarc @mfhepp @@RichardWallis Wat do you think about this approach? It can apply for all vague/ambigous terms.

So I would suggest the following:
1) `action`  remains in core, change the definition or is deprecated and in extension is replaced by `muscleAction` . **DONE**
2) `algorithm`  remains in core with an extended definition.
3) `aspect`  remains in core and is deprecated superseded by `mainContentOfPage` .  **Already existing**
4)  `availableIn`   remains in core and is deprecated superseded by `containedIn` . **Already existing**
5)  `availableService` remains in core and extends the definition
6)  `branch`  remains in core and extends the definition
7)  `cause`  remains in core, change the definition or is deprecated and in extension is replaced by `medicalCause` . **Was done in rejected proposal--- What is sad as we re-do the same work**
8)   `causeOf`  remains in core, deprecated! Its definition is not clear here
9)  `code`  remains in core and extends the definition for general use including medical/health.
10)   `codeValue` remains in core and extends the definition for general use including medical/health.
11)   `codingSystem` remains in core and extends the definition for general use including medical/health.
12)  `comprisedOf` remains in core and extends the definition for general use including medical/health.
13)  `connectedTo` remains in core and extends the definition for general use including medical/health.
14)  `cost` remains in core and extends the definition for general use including medical/health.
15)  `costCategory` remains in core and extends the definition for general use including medical/health.
16)  `costCurrency`  remains in core and extends the definition for general use including medical/health.
17)  `costOrigin`  remains in core and extends the definition for general use including medical/health.
18)  `costPerUnit`  remains in core and extends the definition for general use including medical/health.
18)  `PriceSpecification` remains in core and extends the definition for general use including medical/health.
20)  `diagram` remains in core and extends the definition for general use including medical/health.
21)  `frequency`remains in core, change the definition or is deprecated and in extension is replaced by `drugDoseFrequency` .
22)  `function` remains in core, change the definition or is deprecated and in extension is replaced by `anatomicalFunction` .
23)  `manufacturer` remains in core and extends the definition for general use including medical/health.
24)  `origin` remains in core and extends the definition for general use including medical/health.
25)  `originatesFrom` remains in core and extends the definition
26)  `overview` remains in core and extends the definition
27)  `partOfSystem` remains in core and extends the definition to allow use in the extension
28)  `runsTo` remains in core, change the definition or is deprecated and in extension is replaced by `bloodVesselRunsTo` .
29)  `source`  remains in core, change the definition or is deprecated and in extension is replaced by `bloodVesselOrigin` .
30)  `sourcedFrom` remains in core, change the definition or is deprecated and in extension is replaced by `neuronOrigin` .
31)  `purpose` remains in core and extends the definition for general use including medical/health.
32)  `status`  remains in core, change the definition or is deprecated and in extension is replaced by sub-properties `medicalStatus` + `confirmationStatus` +`encounterStatus` + `medicalRequestStatus` + `medicalCoditionStatus`  .
33)  `usesDevice`  remains in core, change the definition for general use including medical/health.
34)  `warning`  remains in core, change the definition or is deprecated and in extension is replaced by `medicalWarning` .

To be tracked in https://github.com/schemaorg/schemaorg/issues/492

**Comment by twamarc** [comment]
Thanks guys for extensive review.
My suggestion is to keep them as they are now, and move them in extension.
Then in next steps we will keep discussing one by one for improvment.
I will keep this issue opened.
(Tracked under https://github.com/schemaorg/schemaorg/issues/492)

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
