### ISSUE TITLE
Types (concepts) that should remain in core vocabulary

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#37]
Comment from @RichardWallis : 
https://github.com/schemaorg/schemaorg/issues/492
several types that should probably remain as part of the core vocabulary, including:
- Dentist
- Diet
- Hospital
- Midwifery
- Muscle
- Nursing
- OcupationalTherapy
- Optician
- Pharmacy
- Physiotherapy
- Physician
- Patient
- PublicHealth
- Substance
- VeterinaryCare

Potentially it could be argued that MedicalBusiness should also remain in
the core as a foundation for all general medically associated businesses.

That is not to say that the could not be then extended within the health
extension.  For instance Pharmacy could be a subtype of LocalBusiness in
the core, yet be in the domain of medicalSpecialty as defined in the health
extension.

**Comment by davefeg** [comment]
Copy of my comment in: https://github.com/schemaorg/schemaorg/issues/492

@RichardWallis I screened the list and IMHO I think ALL those terms should be and remain in health.schema.org extension. Theyare clear and specialized enough in difference with the previous ones submitted by @mfhepp

**Comment by RichardWallis** [comment]
Hi - sorry for delay in responding.  I’m travelling.

The approach I took when making these suggestions was to look at it from a
general point of view and asking what a, non-medical focussed, person would
expect to see in a general vocabulary to aid discovery in their day-to-day
lives.  For example, what amenities wold they hope/expect to see identified
on the map app on their smartphone.

Hence the suggestion of Hospital, Dentist, Optician, etc.

Substance, as with the property suggestion of ‘action’ has broader meaning
outside of the medical domain, as has Diet, and Muscle.

I fully agree that a health extension may well have more to add to these
terms - for example within ‘health’ Diet could be specialised to identify
it as a LifeStyleModification.

~Richard.

**Comment by twamarc** [comment]
we have to deal one by one with those terms. In the list given here above : 
(tracked under https://github.com/schemaorg/schemaorg/issues/492)

```
Dentist
Diet
Hospital
Midwifery
Muscle
Nursing
OcupationalTherapy
Optician
Pharmacy
Physiotherapy
Physician
Patient
PublicHealth
Substance
VeterinaryCare
```

+1 @davefeg 
It would be hard to convince why they may remain in core. However I quite agree that definition would be improved once moved to extension.
Unless any need for extra discussions, I suggest to close this issue.
If needed we will/on one will create issue term by term

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
