### ISSUE TITLE
Datatypes in health.schema.org extension

### ISSUE THREAD

**Issue by ghost** [twamarc/ScheMed#4]
Would help to extend all datatypes predicates ranges by their corresponding XSD classes

**Comment by twamarc** [comment]
Hi James,
This seems to be an old discussion. See https://lists.w3.org/Archives/Public/public-vocabs/2014Nov/0073.html 
If you follow all the thread you will see it has been higly debated but we never had a conclusion.
Would a revisit be relevant?
