### ISSUE TITLE
support for genetics and pharmacogenetics

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#6]
Picked from Mark Woon:
https://lists.w3.org/Archives/Public/public-schemed/2015Jun/0004.html

Hi,
I'd would love to see support for genetics and pharmacogenetics in the
healthcare schema.
For example, there is no way to even provide metadata for genetics-based
dosing guidelines in MedicalGuideline right now.  An example of such a
guideline can be found here: https://www.pharmgkb.org/guideline/PA166104997
I would like to propose the addition of these types:
- MedicalEntity
  - GeneticSequence
    - Gene
    - Genome
    - Variant
    - VariantCollection
      - Diplotype
      - Haplotype
      - Genotype
        The VariantCollection level is not really necessary, but all it's children
        contains a collection of Variants.
        I can go into more detail on exactly what I think these types should
        be/contain, but wanted to make sure there's consensus on the types that
        should be added.
        Thanks,
        -Mark woon

**Comment by ghost** [comment]
+1
However it's hard here to review or comment. Should help if we have a full .rdfa file (or .ttl) of this so we can review the full model (hierarchy, subClassOf, range/domain, etc). This may help also to integrate it to the existing extension.

@twamarc: can this be communicated as a guide to everyone wishing to add some stuffs to the #healthSchemaOrg extension proposal?

**Comment by twamarc** [comment]
Sure! I will set this on list of requirements.
@markwoon Can you provide a full .rdfa file (or .ttl) from this structure so we can review the full model (hierarchy, subClassOf, range/domain, etc)?

**Comment by twamarc** [comment]
Closed! 
To be continued here: https://github.com/schemaorg/schemaorg/issues/1116
